### PR TITLE
Add Servo.h

### PR DESCRIPTION
**Pull request by anli5005**
This adds a library to control servo motors. Any thoughts?

### CODE REVIEW

**Comment by anli5005** [comment]
👍

**Comment by myracui5** [comment]
hi

**Comment by websiteguy1222** [comment]
/R
/E
/m
🗡 
👍

**Comment by websiteguy1222** [comment]
@anli5005  hi

**Comment by glacialcascade** [comment]
surewhynot.

**Comment by websiteguy1222** [comment]
HOW DO YOU EVEN CODE

**Comment by anli5005** [comment]
@dragonitefll/android needs to take a look at this

**Comment by websiteguy1222** [comment]
wait oops I can't wait what

**Comment by nj-benliu** [comment]
stop commenting ok

**Comment by myracui5** [comment]
🐷🐰🐶🐯🦄

**Comment by anli5005** [comment]
:cheese: :cheese:

**Comment by websiteguy1222** [comment]
💯 @anli5005 🔢 👍

**Comment by glacialcascade** [comment]
if u want to merge make reactions thumbs up,  if you dont thumbs down

**Comment by anli5005** [comment]
🍎 💻 🖱 🖥

**Comment by glacialcascade** [comment]
canibananapls????

**Comment by myracui5** [comment]
comment

**Comment by myracui5** [comment]
:)

**Comment by websiteguy1222** [comment]
😷 🎱 🔢 👾 :qatar: :cn:

**Pull request merged**
