### PR TITLE
Changed color

### PR DESCRIPTION
**Pull request by nj-benliu**
I changed the color to a more calming color. Also, I added some code to make the LED go back and forth, but that’s not in use right now.

### CODE REVIEW

**Review by anli5005 — CHANGES_REQUESTED** [review]
Can we make the indentation neater?

We need to make the code more readable for other team members.

**Comment by nj-benliu** [comment]
I changed the indentation. Is it good now?

**Comment by nj-benliu** [comment]
Guys i made it so that it no longer conflicts with the master branch can we merge it now?

**Comment by websiteguy1222** [comment]
ok
good job :+1:

**Pull request merged**
